title: "Black's Blog"
baseURL: "https://blackblog.net/"
theme: ghostwriter
languageCode: en-us
copyright: blackntt
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Blackntt (Toan Nguyen)
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Black's Blog
  description: This is the black's blog
  github: "https://github.com/blackntt"
  linkedin: "https://linkedin.com/in/XXX/"
  facebook: "https://www.facebook.com/toan.nguyen"
  email: blackntt@gmail.com
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: All
      url: /
      weight: 1
    - name: Algorithms
      url: /post/blockchain/
      weigth: 2
    - name: Blockchain
      url: /post/blockchain/
      weigth: 2
    - name: C++
      url: /post/cplusplus/
      weigth: 2
