title: "Black's Blog"
baseURL: "http://localhost:1313/"
theme: ghostwriter
languageCode: en-us
copyright: blackntt
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Blackntt (Toan Nguyen)
  profile: ""

taxonomies:
  tag: tags
  category: categories

params:
  mainSections:
    - post
  intro: true
  headline: Black's Blog
  description: This is the black's blog
  github: "https://github.com/blackntt"
  linkedin: "https://www.linkedin.com/in/toan-nguyen-7635491a2"
  facebook: "https://www.facebook.com/black.toannguyen"
  email: blackntt@gmail.com
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Algorithms
      url: /categories/algorithms/
      weight: 2
    # - name: Blockchain
    #   url: /categories/blockchain/
    #   weight: 3
    - name: About
      url: /page/about/
      weight: 4
