baseurl: "http://178.128.55.112:1313/"
title: Black's Blog
theme: ghostwriter
languageCode: en-us
copyright: Blackntt (Toan Nguyen)
pygmentsUseClasses: true
pygmentsCodefences: true
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Blackntt (Toan Nguyen)
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Ghostwriter example
  description: Ghostwriter example description
  github: "https://github.com/blackntt"
  linkedin: "https://linkedin.com/in/XXX/"
  facebook: "https://www.facebook.com/toan.nguyen"
  email: blackntt@gmail.com
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:filename/"
